#include "openref_rt595_slot_authenticator.h"
#include <limits.h>
#include <stddef.h>
#include <string.h>
static void fail(openref_rt595_slot_authenticator_t*a){if(a&&a->failures!=UINT32_MAX)++a->failures;}
static void read_fail(openref_rt595_slot_authenticator_t*a){fail(a);if(a&&a->read_failures!=UINT32_MAX)++a->read_failures;}
static bool region(uint32_t b,uint32_t n){return n>0u&&b<=UINT32_MAX-n;}
static bool overlap(uint32_t a,uint32_t an,uint32_t b,uint32_t bn){return a<b+bn&&b<a+an;}
bool openref_rt595_slot_authenticator_init(openref_rt595_slot_authenticator_t*a,openref_rt595_slot_reader_t r,const openref_update_platform_t*p,openref_update_crypto_t c,uint32_t m0,uint32_t i0,uint32_t n0,uint32_t m1,uint32_t i1,uint32_t n1){openref_update_verifier_t v;if(!a||!r.read||!p||!region(m0,OPENREF_UPDATE_MANIFEST_BYTES)||!region(m1,OPENREF_UPDATE_MANIFEST_BYTES)||!region(i0,n0)||!region(i1,n1)||overlap(m0,OPENREF_UPDATE_MANIFEST_BYTES,i0,n0)||overlap(m1,OPENREF_UPDATE_MANIFEST_BYTES,i1,n1)||overlap(m0,OPENREF_UPDATE_MANIFEST_BYTES,m1,OPENREF_UPDATE_MANIFEST_BYTES)||overlap(m0,OPENREF_UPDATE_MANIFEST_BYTES,i1,n1)||overlap(m1,OPENREF_UPDATE_MANIFEST_BYTES,i0,n0)||overlap(i0,n0,i1,n1)||p->maximum_image_bytes>n0||p->maximum_image_bytes>n1||!openref_update_verifier_init(&v,p,c))return false;memset(a,0,sizeof(*a));a->reader=r;a->platform=*p;a->crypto=c;a->manifest_base[0]=m0;a->image_base[0]=i0;a->image_capacity[0]=n0;a->manifest_base[1]=m1;a->image_base[1]=i1;a->image_capacity[1]=n1;a->initialized=true;return true;}
bool openref_rt595_slot_authenticate(openref_rt595_slot_authenticator_t*a,uint8_t candidate,uint8_t running,openref_boot_slot_t*out){uint8_t manifest[OPENREF_UPDATE_MANIFEST_BYTES];uint32_t offset=0;openref_update_verifier_t v;if(out)memset(out,0,sizeof(*out));if(a&&candidate<=1u)a->authenticated_image_size[candidate]=0u;if(!a||!a->initialized||!out||candidate>1u||(running>1u&&running!=OPENREF_BOOT_NO_SLOT)||candidate==running){fail(a);return false;}if(!a->reader.read(a->reader.context,a->manifest_base[candidate],manifest,sizeof(manifest))){read_fail(a);return false;}if(!openref_update_verifier_init(&v,&a->platform,a->crypto)||!openref_update_verifier_begin(&v,manifest)||v.manifest.image_size>a->image_capacity[candidate]){fail(a);return false;}while(offset<v.manifest.image_size){uint8_t chunk[OPENREF_RT595_SLOT_AUTH_CHUNK_BYTES];uint32_t n=v.manifest.image_size-offset;if(n>sizeof(chunk))n=sizeof(chunk);if(!a->reader.read(a->reader.context,a->image_base[candidate]+offset,chunk,n)){read_fail(a);return false;}if(!openref_update_verifier_write(&v,chunk,n)){fail(a);return false;}offset+=n;}if(!openref_update_verifier_finish(&v)){fail(a);return false;}out->present=true;out->authenticated=true;out->version=v.manifest.image_version;a->authenticated_image_size[candidate]=v.manifest.image_size;return true;}
