#include "openref_rt595_audio_io.h"
#include <limits.h>
#include <stddef.h>
#include <string.h>
static void inc(uint32_t*v){if(*v!=UINT32_MAX)++*v;}
bool openref_rt595_audio_io_init(openref_rt595_audio_io_t*s,const openref_rt595_audio_io_ops_t*o){if(!s||!o||!o->capture||!o->playout||!o->abort||!o->enter_critical||!o->exit_critical)return false;memset(s,0,sizeof(*s));s->ops=*o;s->initialized=true;s->capture_active=o->capture(o->context,s->capture[0],OPENREF_RT595_AUDIO_IO_BLOCK_SAMPLES);s->playout_active=o->playout(o->context,s->playout[0],OPENREF_RT595_AUDIO_IO_BLOCK_SAMPLES);if(!s->capture_active||!s->playout_active){inc(&s->dma_failures);o->abort(o->context);s->initialized=false;return false;}return true;}
void openref_rt595_audio_io_capture_complete(openref_rt595_audio_io_t*s,bool ok){if(!s||!s->initialized||!s->capture_active)return;uint8_t done=s->capture_index,next=done^1u;s->capture_active=false;if(!ok)inc(&s->dma_failures);else{if(s->capture_ready[done])inc(&s->capture_overruns);s->capture_ready[done]=true;inc(&s->capture_blocks);}if(s->capture_ready[next]){s->capture_ready[next]=false;inc(&s->capture_overruns);}s->capture_index=next;s->capture_active=s->ops.capture(s->ops.context,s->capture[next],OPENREF_RT595_AUDIO_IO_BLOCK_SAMPLES);if(!s->capture_active)inc(&s->dma_failures);}
void openref_rt595_audio_io_playout_complete(openref_rt595_audio_io_t*s,bool ok){if(!s||!s->initialized||!s->playout_active)return;uint8_t next=s->playout_index^1u;s->playout_active=false;if(!ok)inc(&s->dma_failures);else inc(&s->playout_blocks);if(!s->playout_ready[next]){memset(s->playout[next],0,sizeof(s->playout[next]));inc(&s->playout_underruns);}s->playout_ready[next]=false;s->playout_index=next;s->playout_active=s->ops.playout(s->ops.context,s->playout[next],OPENREF_RT595_AUDIO_IO_BLOCK_SAMPLES);if(!s->playout_active)inc(&s->dma_failures);}
bool openref_rt595_audio_io_take_capture(openref_rt595_audio_io_t*s,int16_t out[OPENREF_RT595_AUDIO_IO_BLOCK_SAMPLES]){if(!s||!s->initialized||!out)return false;s->ops.enter_critical(s->ops.context);uint8_t i=s->capture_index^1u;if(!s->capture_ready[i]){i=s->capture_index;if(!s->capture_ready[i]){s->ops.exit_critical(s->ops.context);return false;}}memcpy(out,s->capture[i],sizeof(s->capture[i]));s->capture_ready[i]=false;s->ops.exit_critical(s->ops.context);return true;}
bool openref_rt595_audio_io_submit_playout(openref_rt595_audio_io_t*s,const int16_t in[OPENREF_RT595_AUDIO_IO_BLOCK_SAMPLES]){if(!s||!s->initialized||!in)return false;s->ops.enter_critical(s->ops.context);uint8_t i=s->playout_index^1u;if(s->playout_ready[i]){s->ops.exit_critical(s->ops.context);return false;}memcpy(s->playout[i],in,sizeof(s->playout[i]));s->playout_ready[i]=true;s->ops.exit_critical(s->ops.context);return true;}
void openref_rt595_audio_io_stop(openref_rt595_audio_io_t*s){if(s&&s->initialized){s->ops.abort(s->ops.context);s->initialized=false;s->capture_active=false;s->playout_active=false;}}
