#include "openref_rt595_audio_io_mcux.h"
#include <stddef.h>
static void capture_done(DMIC_Type*b,dmic_dma_handle_t*h,status_t s,void*u){(void)b;(void)h;openref_rt595_audio_io_mcux_t*a=u;openref_rt595_audio_io_capture_complete(&a->io,s==kStatus_Success);}
static void playout_done(I2S_Type*b,i2s_dma_handle_t*h,status_t s,void*u){(void)b;(void)h;openref_rt595_audio_io_mcux_t*a=u;openref_rt595_audio_io_playout_complete(&a->io,s==kStatus_Success);}
static bool capture(void*c,int16_t*d,uint16_t n){openref_rt595_audio_io_mcux_t*a=c;dmic_transfer_t t={0};t.data=d;t.dataWidth=(uint8_t)kDMA_Transfer16BitWidth;t.dataSize=(size_t)n*sizeof(*d);return DMIC_TransferReceiveDMA(a->config.dmic,&a->dmic_handle,&t,a->config.dmic_channel)==kStatus_Success;}
static bool playout(void*c,int16_t*d,uint16_t n){openref_rt595_audio_io_mcux_t*a=c;if(n!=OPENREF_RT595_AUDIO_IO_BLOCK_SAMPLES)return false;for(uint16_t i=0;i<n;i++){a->stereo[2u*i]=d[i];a->stereo[2u*i+1u]=d[i];}i2s_transfer_t t={0};t.data=(uint8_t*)a->stereo;t.dataSize=sizeof(a->stereo);return I2S_TxTransferSendDMA(a->config.i2s,&a->i2s_handle,t)==kStatus_Success;}
static void abort_io(void*c){openref_rt595_audio_io_mcux_t*a=c;DMIC_TransferAbortReceiveDMA(a->config.dmic,&a->dmic_handle);I2S_TransferAbortDMA(a->config.i2s,&a->i2s_handle);}
static void enter_critical(void*c){openref_rt595_audio_io_mcux_t*a=c;a->critical_primask=__get_PRIMASK();__disable_irq();}
static void exit_critical(void*c){openref_rt595_audio_io_mcux_t*a=c;if(a->critical_primask==0u)__enable_irq();}
bool openref_rt595_audio_io_mcux_init(openref_rt595_audio_io_mcux_t*a,const openref_rt595_audio_io_mcux_config_t*c){if(!a||!c||!c->dmic||!c->i2s||!c->dma||c->dmic_dma_channel==c->i2s_dma_channel)return false;a->config=*c;DMA_EnableChannel(c->dma,c->dmic_dma_channel);DMA_EnableChannel(c->dma,c->i2s_dma_channel);DMA_CreateHandle(&a->dmic_dma,c->dma,c->dmic_dma_channel);DMA_CreateHandle(&a->i2s_dma,c->dma,c->i2s_dma_channel);if(DMIC_TransferCreateHandleDMA(c->dmic,&a->dmic_handle,capture_done,a,&a->dmic_dma)!=kStatus_Success)return false;I2S_TxTransferCreateHandleDMA(c->i2s,&a->i2s_handle,&a->i2s_dma,playout_done,a);openref_rt595_audio_io_ops_t o={.capture=capture,.playout=playout,.abort=abort_io,.enter_critical=enter_critical,.exit_critical=exit_critical,.context=a};return openref_rt595_audio_io_init(&a->io,&o);}
