param(
    [string]$ProjectRoot = "$env:USERPROFILE\SimplicityStudio\v6_workspace\rail_soc_railtest",
    [string]$RepoRoot = (Resolve-Path "$PSScriptRoot\..").Path,
    [switch]$InstallAppShim,
    [switch]$EnableAutoTx,
    [switch]$EnableAutoRx,
    [switch]$EnableAutoRole,
    [switch]$EnableGpioMarkers,
    [string]$BuildMarker = "",
    [string]$QueueMarker = "",
    [string]$StartMarker = "",
    [string]$DoneMarker = ""
)

$ErrorActionPreference = "Stop"

function Convert-OpenRefGpioMarker {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Marker
    )

    $normalized = $Marker.Trim().ToUpperInvariant()
    if ($normalized -notmatch "^P?([A-Z])(\d{1,2})$") {
        throw "Invalid GPIO marker '$Marker'. Use labels like B0, PB3, or A5."
    }

    $pin = [int]$Matches[2]
    if ($pin -lt 0 -or $pin -gt 15) {
        throw "Invalid GPIO marker '$Marker'. Pin must be in the range 0-15."
    }

    return @{
        Port = $Matches[1]
        Pin = $pin
    }
}

function Add-OpenRefGpioMarkerDefinitions {
    param(
        [string[]]$Definitions,
        [string]$Label,
        [string]$Marker
    )

    if ([string]::IsNullOrWhiteSpace($Marker)) {
        return $Definitions
    }

    $gpio = Convert-OpenRefGpioMarker -Marker $Marker
    $Definitions += "OPENREF_GPIO_$($Label)_PORT=gpioPort$($gpio.Port)"
    $Definitions += "OPENREF_GPIO_$($Label)_PIN=$($gpio.Pin)"
    return $Definitions
}

$projectRootPath = Resolve-Path $ProjectRoot
$repoRootPath = Resolve-Path $RepoRoot
$overlayRoot = Join-Path $projectRootPath "openref"
$overlayCommon = Join-Path $overlayRoot "common"
$overlayFg23 = Join-Path $overlayRoot "fg23"
$cmakeOverlay = Join-Path $projectRootPath "cmake_gcc\rail_soc_railtest_project.cmake"

New-Item -ItemType Directory -Force -Path $overlayCommon | Out-Null
New-Item -ItemType Directory -Force -Path $overlayFg23 | Out-Null

Copy-Item -Force -Path (Join-Path $repoRootPath "firmware\common\openref_proto0_packet.h") -Destination $overlayCommon
Copy-Item -Force -Path (Join-Path $repoRootPath "firmware\common\openref_proto0_packet.c") -Destination $overlayCommon
Copy-Item -Force -Path (Join-Path $repoRootPath "firmware\common\openref_radio.h") -Destination $overlayCommon
Copy-Item -Force -Path (Join-Path $repoRootPath "firmware\prototype0\fg23\src\openref_packet_pair.h") -Destination $overlayFg23
Copy-Item -Force -Path (Join-Path $repoRootPath "firmware\prototype0\fg23\src\openref_packet_pair.c") -Destination $overlayFg23
Copy-Item -Force -Path (Join-Path $repoRootPath "firmware\prototype0\fg23\src\openref_app.h") -Destination $overlayFg23
Copy-Item -Force -Path (Join-Path $repoRootPath "firmware\prototype0\fg23\src\openref_app.c") -Destination $overlayFg23

$cmake = @"
# OpenRef local overlay. Generated by tools/install_openref_fg23_overlay.ps1.
# This file is included by cmake_gcc/CMakeLists.txt when present.

target_sources(rail_soc_railtest PRIVATE
    `${CMAKE_CURRENT_LIST_DIR}/../openref/common/openref_proto0_packet.c
    `${CMAKE_CURRENT_LIST_DIR}/../openref/fg23/openref_packet_pair.c
    `${CMAKE_CURRENT_LIST_DIR}/../openref/fg23/openref_app.c
)

target_include_directories(rail_soc_railtest PRIVATE
    `${CMAKE_CURRENT_LIST_DIR}/../openref/common
    `${CMAKE_CURRENT_LIST_DIR}/../openref/fg23
)

target_include_directories(slc PRIVATE
    `${CMAKE_CURRENT_LIST_DIR}/../openref/common
    `${CMAKE_CURRENT_LIST_DIR}/../openref/fg23
)
"@

if ($EnableAutoTx) {
    $cmake += @"

target_compile_definitions(rail_soc_railtest PRIVATE OPENREF_APP_AUTOTX=1)
"@
}

if ($EnableAutoRx) {
    $cmake += @"

target_compile_definitions(rail_soc_railtest PRIVATE OPENREF_APP_AUTORX=1)
"@
}

if ($EnableAutoRole) {
    $cmake += @"

target_compile_definitions(rail_soc_railtest PRIVATE OPENREF_APP_AUTOROLE=1)
"@
}

$gpioMarkersRequested = $EnableGpioMarkers -or
    -not [string]::IsNullOrWhiteSpace($BuildMarker) -or
    -not [string]::IsNullOrWhiteSpace($QueueMarker) -or
    -not [string]::IsNullOrWhiteSpace($StartMarker) -or
    -not [string]::IsNullOrWhiteSpace($DoneMarker)

if ($gpioMarkersRequested) {
    if (-not $EnableAutoRole) {
        throw "GPIO markers require -EnableAutoRole because marker hooks are compiled only for the AutoRole runtime."
    }
    if ([string]::IsNullOrWhiteSpace($BuildMarker) -and
        [string]::IsNullOrWhiteSpace($QueueMarker) -and
        [string]::IsNullOrWhiteSpace($StartMarker) -and
        [string]::IsNullOrWhiteSpace($DoneMarker)) {
        throw "GPIO markers were requested, but no marker pins were supplied. Add at least one of -BuildMarker, -QueueMarker, -StartMarker, or -DoneMarker."
    }

    $markerDefinitions = @("OPENREF_APP_GPIO_MARKERS=1")
    $markerDefinitions = Add-OpenRefGpioMarkerDefinitions -Definitions $markerDefinitions -Label "BUILD" -Marker $BuildMarker
    $markerDefinitions = Add-OpenRefGpioMarkerDefinitions -Definitions $markerDefinitions -Label "QUEUE" -Marker $QueueMarker
    $markerDefinitions = Add-OpenRefGpioMarkerDefinitions -Definitions $markerDefinitions -Label "START" -Marker $StartMarker
    $markerDefinitions = Add-OpenRefGpioMarkerDefinitions -Definitions $markerDefinitions -Label "DONE" -Marker $DoneMarker
    $markerDefinitionText = $markerDefinitions -join " "

    $cmake += @"

target_compile_definitions(rail_soc_railtest PRIVATE $markerDefinitionText)
"@
}

Set-Content -Path $cmakeOverlay -Value $cmake -Encoding ASCII

if ($InstallAppShim) {
    $appFile = Join-Path $projectRootPath "app.c"
    $backupDir = Join-Path $projectRootPath ".openref-backup"
    $backupFile = Join-Path $backupDir "app.c"
    New-Item -ItemType Directory -Force -Path $backupDir | Out-Null
    if (-not (Test-Path $backupFile)) {
        Copy-Item -Force -Path $appFile -Destination $backupFile
    }

    $appShim = @"
#include "app.h"
#include "openref_app.h"

void app_init(void)
{
  openref_app_init();
}

void app_process_action(void)
{
  openref_app_process_action();
}
"@

    Set-Content -Path $appFile -Value $appShim -Encoding ASCII
    Write-Host "Installed OpenRef app shim:"
    Write-Host "  $appFile"
    Write-Host "  Backup: $backupFile"
}

Write-Host "Installed OpenRef overlay:"
Write-Host "  $overlayRoot"
Write-Host "  $cmakeOverlay"
